apiVersion: v1
kind: Secret
metadata:
  name: hotelier-secrets
  namespace: hotelier
type: Opaque
stringData:
  # -- JWT --
  Jwt__Key: qR7tYxFm2X8W5yO0L8tE3Zs9eVVj9u4cQ7xN1wT2pK6rP0uH3M5bY8nA1zD4kV9R
  Jwt__Issuer: hotelier-identity
  Jwt__Audience: hotelier
  # -- RabbitMQ --
  Rabbit__Password: guest
  # -- PostgreSQL (used in connection strings) --
  POSTGRES_USER: hotelier
  POSTGRES_PASSWORD: hotelier
  # -- MongoDB --
  MONGO_USER: hotelier
  MONGO_PASSWORD: hotelier
