global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "availability-service"
    static_configs:
      - targets: ["availability-service:8080"]

  - job_name: "accommodation-service"
    static_configs:
      - targets: ["accommodation-service:8080"]

  - job_name: "identity-service"
    static_configs:
      - targets: ["identity-service:8080"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8080"]

  - job_name: "rating-service"
    static_configs:
      - targets: ["rating-service:8080"]

  - job_name: "reservation-service"
    static_configs:
      - targets: ["reservation-service:8080"]

  - job_name: "search-service"
    static_configs:
      - targets: ["search-service:8080"]

  - job_name: "cdn-service"
    static_configs:
      - targets: ["cdn-service:8080"]
